min_font_size: 15
max_font_size: 30
max_content_length: 15
image_width: 224
image_height: 224
contents:
  -
    id: company
    corpus_path: /Users/qianhuan/Desktop/projects/make_datasets/data/corpus/company.txt
    w: 1.0
seal_base:
  min_radius: 100
  max_radius: 110
  min_circle_width: 4
  max_circle_width: 9
  min_star_radius: 20
  max_star_radius: 35
  min_interval_angle: 18
  max_interval_angle: 22
